import { StyleSheet } from "react-native";
import { theme } from "./colors";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.grey,
        paddingHorizontal: 50,
        paddingTop: 50,
    },
    title: {
        flex: 0.5,
        justifyContent: "center",
        alignItems: "flex-start",
        marginBottom: 30,
    },
    titleText: {
        color: "black",
        fontSize: 45,
        fontWeight: "800",
    },
    subtitleText: {
        color: "black",
        fontSize: 25,
        fontWeight: "400",
        marginTop: -5,
    },
    body: {
        justifyContent: "space-between",
        flexDirection: "row",
    },
    imageBody: {
        backgroundColor: "white",
        width: 350,
        height: 500,
        borderRadius: 30,
        paddingHorizontal: 25,
        paddingTop: 30,
        alignItems: "flex-start",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.15,
        shadowRadius: 2.04,
        elevation: 4,
    },
    imageContainer: {
        width: 300,
        height: 300,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: theme.grey,
        marginTop: 20,
    },
    imageText: {
        color: "black",
        fontSize: 25,
        fontWeight: "500",
    },
    image: {
        width: "100%",
        height: "100%",
        borderRadius: 20,
    },
    importText: {
        color: "black",
        fontSize: 13,
        fontWeight: "400",
        paddingTop: 5,
    },
    buttonContainer: {
        borderRadius: 20,
        flexDirection: "row",
        width: "100%",
        justifyContent: "center",
        marginTop: 25,
    },
    button: {
        backgroundColor: "black",
        width: "100%",
        alignItems: "center",
        paddingVertical: 15,
        borderRadius: 20,
    },
    buttonText: {
        color: "white",
        fontSize: 18,
        fontWeight: "bold",
    },
    distribution: {
        backgroundColor: "white",
        width: 450,
        height: 500,
        borderRadius: 30,
        paddingLeft: 25,
        paddingTop: 30,
        alignItems: "flex-start",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.15,
        shadowRadius: 2.04,
        elevation: 4,
    },
    distributionTitle: {
        color: "black",
        fontSize: 25,
        fontWeight: "500",
    },
    distributionBody: {
        backgroundColor: theme.grey,
        width: 400,
        height: 300,
        borderRadius: 30,
        marginTop: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    pieTitle: {
        marginTop: 10,
        fontSize: 20,
        fontWeight: "500",
    },
    status: {
        backgroundColor: "white",
        width: 350,
        height: 500,
        borderRadius: 30,
        paddingTop: 30,
        paddingHorizontal: 25,
        alignItems: "flex-start",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.15,
        shadowRadius: 2.04,
        elevation: 4,
    },
    statusTitle: {
        color: "black",
        fontSize: 25,
        fontWeight: "500",
        marginBottom: 20,
    },
    aerosolTypeText: {
        color: "black",
        fontSize: 20,
        fontWeight: "500",
    },
    aerosolAccuracyText: {
        color: "#00000090",
        fontSize: 19,
        fontWeight: "400",
    },
    statusContainer: {
        marginBottom: 15,
        backgroundColor: theme.grey,
        paddingHorizontal: 20,
        height: 100,
        width: 300,
        borderRadius: 20,
        alignItems: "left",
        justifyContent: "flex-start",
        paddingTop: 15,
    },
    accuracy: {
        width: 270,
        height: 50,
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "space-between",
        paddingRight: 5,
    },
    navigatorContainer: {
        borderRadius: 20,
        flexDirection: "row",
        width: "100%",
        justifyContent: "center",
        alignItems: "center",
        marginTop: 20,
        marginBottom: -30,
    },
    navigator: {
        backgroundColor: "white",
        width: "15%",
        height: 50,
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "space-between",
        paddingVertical: 5,
        paddingLeft: 15,
        paddingRight: 15,
        borderRadius: 20,
    },
    navigatorTab: {
        width: "48%",
        height: "100%",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 10,
    },
    navigatorText: {
        color: "black",
        fontSize: 15,
        fontWeight: "500",
    },
    body2: {
        justifyContent: "space-between",
        flexDirection: "row",
    },
    mapBody: {
        backgroundColor: "white",
        width: 750,
        height: 500,
        borderRadius: 30,
        paddingHorizontal: 25,
        paddingTop: 30,
        alignItems: "flex-start",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.15,
        shadowRadius: 2.04,
        elevation: 4,
    },
    mapText: {
        color: "black",
        fontSize: 25,
        fontWeight: "500",
    },
    map: {
        width: "100%",
        height: "70%",
        marginTop: 20,
        marginBottom: 20,
    },
    addressBody: {
        backgroundColor: "white",
        width: "100%",
        height: "10%",
        borderRadius: 10,
        paddingHorizontal: 25,
        paddingTop: 10,
        alignItems: "flex-start",
        flexDirection: "row",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.15,
        shadowRadius: 2.04,
        elevation: 4,
    },
    address: {
        fontSize: 15,
        fontWeight: "500",
    },
    weatherBody: {
        backgroundColor: "white",
        width: 410,
        height: 500,
        borderRadius: 30,
        paddingHorizontal: 25,
        paddingTop: 30,
        alignItems: "flex-start",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.15,
        shadowRadius: 2.04,
        elevation: 4,
    },
    weatherText: {
        color: "black",
        fontSize: 25,
        fontWeight: "500",
    },
});
